### PR TITLE
log an error when there isn't a primary key

### PR DESCRIPTION
**Pull request by abkieling**
I've changed 'defaultPrimaryKeyFn' to throw an Error when it can't find a primary key property in the entity. The effect of that is an empty table and a nice error message in the console. I think it's good enough, but can change the UI if necessary.

I think the code that adds the index to the rows isn't required anymore. Is that right?

### CODE REVIEW

**Comment by gashcrumb** [comment]
@alexkieling sorry, would you mind rebasing this whenever you get a chance?

**Comment by abkieling** [comment]
No problem. I'll do that tonight.

**Comment by abkieling** [comment]
Code rebased

**Comment by gashcrumb** [comment]
Great, thanks @alexkieling!

**Pull request merged**
