### PR TITLE
make table scrollable when attribute maxBodyHeight is defined

### LINKED ISSUE #4: add an attribute to specify a maximum tbody height
which could then use some JS to set things correctly on the table to allow scrolling of the table body but leaving the headers fixed.

example of how to do it here:
http://stackoverflow.com/a/17380697/2068211

looks like using width calculations and JS might help

### PR DESCRIPTION
**Pull request by abkieling**
Added a new attribute called maxBodyHeight, which when defined transforms the table into a scrollable table. One table contains the header and another table contains the body. A div wraps the body table to add the scroll.
Fixes #4

### CODE REVIEW

**Comment by gashcrumb** [comment]
Looking good!  Can you do me a favor and run `gulp build` and also check in the changed files under `dist/`?  Thanks!

**Comment by abkieling** [comment]
Added the files under dist/. Let me know if there are any issues.

**Comment by gashcrumb** [comment]
@alexkieling thanks!

**Comment by abkieling** [comment]
Stan, the width of the header cell that stays on top of the scrollbar will have to be dynamically set based on the scrollbar width, which is not the same on all browsers. I just noticed that Edge's scrollbar is narrower.

**Pull request merged**
