### PR TITLE
Move dynatree Camel icons to hawtio-ui

### PR DESCRIPTION
**Pull request by tadayosi**
@alexkieling @astefanutti @gashcrumb Since I'm not sure if I'm doing a right thing please review it before merging it to master!

Note I also sorted out `gulpfile.js` here to make embedding images to css work.

### CODE REVIEW

**Comment by abkieling** [comment]
Interesting. I didn't know the images are included in the CSS file as base64.
Why is it better to have the Camel plugin tree icons in hawtio-ui and not in hawtio-integration where the plugin is?

**Comment by astefanutti** [comment]
I did the same for the JMX plugin @a6b543d5a9e8a64bdf9ffc1941b362abe1930be7 as this causes the pathes from the tree CSS being wrong during development (and currently demos). Surprisingly, I didn't notice the issue for the Camel icons, but I guess this is the point of this PR.

That being said, that was more a quick fix and I'm half satisfied with the solution. I would tend to prefer to have the images included in the corresponding plugins, as it kind of defeats the purpose of the Hawtio v2 modular architecture.

The current approach for packaging images in the final application is to rewrite URL, e.g., in the OpenShift JVM console: https://github.com/hawtio/openshift-jvm/blob/9cd703231dfebba04d86524010b87d9a220001bf/gulpfile.js#L371.

That may be a solution to be replicated in the JMX and Camel plugins. Another would be to be able to move the CSS bits into the corresponding modules and adjust the pathes.

In the short term, it may be better to only move the actually referenced icons in order to avoid cluttering the hawtio-ui module with module specific bits: https://github.com/hawtio/hawtio-ui/blob/8c103aa9c6ce77f5f9c08331176438d9d3159f6b/plugins/vendor/dynatree-icons.less#L150-L182.

**Comment by gashcrumb** [comment]
Yeah, really images for a component should stay with that component, and then we can sort out how they're packaged in the final assembly.  In fabric8-console as an example we go and look for `img`, `images` and better still `resources`:

https://github.com/fabric8io/fabric8-console/blob/master/gulpfile.js#L610-L627

Components should keep their stuff under `img` or `images` or under `resources` and use relative paths when referring to them.  I think issues in camel specifically are often due to the plugin's code using an absolute path to refer to icons/images.

Using `resources` for everything works pretty well, for example [hawtio-kube3d](https://github.com/hawtio/hawtio-kube3d) has lots of [images and sound clips](https://github.com/hawtio/hawtio-kube3d/tree/master/resources) too.

**Comment by tadayosi** [comment]
Thanks all!  Yeah, I agree that each plugin should have corresponding resources in it. By this way Hawtio plugins will become more cohesive and independent with each other. I'll withdraw this pull req then (and maybe hawtio/hawtio-jmx@a6b543d5a9e8a64bdf9ffc1941b362abe1930be7 too?).

@gashcrumb By the way, what about the 'embed-images' task in `gulpfile.js`?  Won't we use it any longer and can we remove it safely all together?

**Comment by gashcrumb** [comment]
If it's the task I'm thinking of, I was hoping to solve the packaging issue
with images by base64 encoding them and embedding them in the CSS files and
HTML templates.  But there's size limitations with that, so I didn't pursue
it much further.  We can probably remove that, think we'll just want to
make sure the icon example page still works.

**Pull request closed without merging**
