### PR TITLE
concatenate third-party .js and .css files into hawtio-ui.js/css

### PR DESCRIPTION
**Pull request by abkieling**
Made the changes as discussed. The widgets look OK in the demo site. Please test again to confirm and let me know what you think.

About the dependencies from other projects, I think we could change those projects to depend on the current version of hawtio-ui and remove the ^ from the version number. When the next version of hawtio-ui is released, those projects won't be affected.

### CODE REVIEW

**Comment by gashcrumb** [comment]
Seems to work fine here.  Only thing is dist/hawtio-ui-test.js and dist/hawtio-ui-test.css wind up showing up as untracked files after building.  Wonder, maybe it's worth just adding those files to the .gitignore?  They're only used by the demo site and for development.

**Comment by abkieling** [comment]
Good point. Maybe it would be better to copy them to a different folder, not `/dist`. If we decide to keep them in `dist`, we should at least ignore them in the bower configuration. Do you think copying them to the `website` folder makes sense?

**Comment by gashcrumb** [comment]
So there's a 'site' task that we use to create the ui.hawt.io website, if you do `gulp site` it'll create the folder structure for the website under `site`.  Now that I think about it, we do reference those files in `index.html`, so probably best to keep them part of the repo.

**Comment by abkieling** [comment]
Shall we copy `hawtio-ui-test.js` and `hawtio-ui-test.css` to `dist/` and ignore them in the bower configuration file or copy them somewhere else and adjust `index.html` and the gulp `site` task accordingly?

**Comment by gashcrumb** [comment]
Let's keep 'em going to `dist/` and ignore them in the bower config, then the `site` task shouldn't need changing.

**Comment by abkieling** [comment]
OK, I'll do that tonight.

**Comment by abkieling** [comment]
Amended the commit to keep `hawtio-ui-test.*` in `dist` and moved `dist/fonts` do `plugins/vendor/fonts`. 
Could you please check where the new 'clean-dist' gulp task should be added in the build pipeline?

**Comment by gashcrumb** [comment]
Yep, works here.  I think yeah, probably worth adding `clean-dist` to the `build` task to ensure any cruft is cleaned up.

**Comment by abkieling** [comment]
Updated `gulpfile.js` to clean the `dist` folder before running the `build` task.

**Comment by abkieling** [comment]
Should `dist/fonts` be added to git?

**Comment by gashcrumb** [comment]
Yeah, I think it needs to be actually, as other downstream components like fabric8-console need those font files.  I guess the location doesn't matter that terribly though, [here](https://github.com/fabric8io/fabric8-console/blob/master/gulpfile.js#L539-L546) we just look for the individual font files and then flatten the path, so they all wind up in 'fonts' in the final assembly.  So really, as long as you do `bower install` on this component and the font files are part of it then it should be fine.

**Comment by abkieling** [comment]
OK, I got it. I think we could simplify the build process and, instead of copying the fonts to `dist/`, just leave the `fonts/` folder in the hawtio-ui's root folder. As long as we don't ignore the folder in the bower config, it will be available.

**Comment by abkieling** [comment]
Decided to leave `fonts/` in `dist/` and not clean it, exactly how it's always been done. There is a `build-clean` task to remove the files created by the `build` task and there is a `build-example-clean` task to remove the files created by the `build-example` task.

**Comment by gashcrumb** [comment]
Checked out fine here, thanks!

**Pull request merged**
